### ISSUE TITLE
ABKTriggerPropertyFilter Crash

### ISSUE THREAD

**Issue by msadoon** [Appboy/appboy-segment-ios#67]
Hi all, 

Wanted to report this crash, happens consistently on iOS 16.2, iPhone SE 2020.

Debugger info:
```
2023-02-01 11:09:28.701035-0500 Kickstarter[12772:2425560] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x85a8979a540d1bd9
2023-02-01 11:09:28.703307-0500 Kickstarter[12772:2425560] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x85a8979a540d1bd9'
*** First throw call stack:
(0x1b9a2de48 0x1b2d038d8 0x1b9ba282c 0x1b9a43f60 0x1b9aac330 0x1b4333264 0x1b3e1ae78 0x1b3e1ad78 0x10ebdce68 0x10ebdd020 0x10ebdc27c 0x10ebdc204 0x10ec4c458 0x1b9a2e360 0x1b9a49690 0x10ec4c364 0x1b9a2e360 0x1b9ab50c0 0x10ec4c1dc 0x10ec27010 0x10ec38ab8 0x10ec0ac44 0x10ec0aafc 0x10ec0be50 0x10ec0bc4c 0x10ec0a9d4 0x1b3e540f0 0x1b3e28240 0x1b3e281d0 0x1b3de9578 0x1b3de92ac 0x1b3dee9c0 0x10519f1d0 0x10518e05c 0x1051911e8 0x105190438 0x1051a2478 0x1051a2e74 0x207ab5dbc 0x207ab5b98)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x85a8979a540d1bd9'
terminating with uncaught exception of type NSException

```

Thread debugger:
```
Thread 40 Queue : NSOperationQueue 0x15930bde0 (QOS: UNSPECIFIED) (concurrent)
#0	0x00000001f739f160 in __pthread_kill ()
#1	0x0000000207abc1ac in pthread_kill ()
#2	0x00000001c10a4c8c in abort ()
#3	0x00000002079fbb8c in abort_message ()
#4	0x00000002079eba80 in demangling_terminate_handler() ()
#5	0x00000001b2d09d3c in _objc_terminate() ()
#6	0x00000002079faf28 in std::__terminate(void (*)()) ()
#7	0x00000002079faec4 in std::terminate() ()
#8	0x00000001b2d1fbec in objc_terminate ()
#9	0x000000010518e070 in _dispatch_client_callout ()
#10	0x00000001051911e8 in _dispatch_continuation_pop ()
#11	0x0000000105190438 in _dispatch_async_redirect_invoke ()
#12	0x00000001051a2478 in _dispatch_root_queue_drain ()
#13	0x00000001051a2e74 in _dispatch_worker_thread2 ()
#14	0x0000000207ab5dbc in _pthread_wqthread ()
Thread#0	0x00000001b9a2de48 in __exceptionPreprocess ()
#1	0x00000001b2d038d8 in objc_exception_throw ()
#2	0x00000001b9ba282c in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#3	0x00000001b9a43f60 in ___forwarding___ ()
#4	0x00000001b9aac330 in _CF_forwarding_prep_0 ()
#5	0x00000001b4333264 in getObjectValue ()
#6	0x00000001b3e1ae78 in -[NSNumberFormatter getObjectValue:forString:errorDescription:] ()
#7	0x00000001b3e1ad78 in -[NSNumberFormatter numberFromString:] ()
#8	0x000000010ebdce68 in -[ABKTriggerPropertyFilter validatePropertyValueType:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:194
#9	0x000000010ebdd020 in -[ABKTriggerPropertyFilter validatedValue:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:204
#10	0x000000010ebdc27c in -[ABKTriggerPropertyFilter matchValue:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:78
#11	0x000000010ebdc204 in -[ABKTriggerPropertyFilter matchProperties:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:72
#12	0x000000010ec4c458 in __38-[ABKPropertyTrigger matchProperties:]_block_invoke_2 at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:49
#13	0x00000001b9a2e360 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#14	0x00000001b9a49690 in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#15	0x000000010ec4c364 in __38-[ABKPropertyTrigger matchProperties:]_block_invoke at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:48
#16	0x00000001b9a2e360 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#17	0x00000001b9ab50c0 in -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] ()
#18	0x000000010ec4c1dc in -[ABKPropertyTrigger matchProperties:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:45
#19	0x000000010ec27010 in -[ABKCustomEventPropertyTrigger match:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKCustomEventPropertyTrigger.m:21
#20	0x000000010ec38ab8 in -[ABKTriggeredAction respondsToTriggerEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerActions/ABKTriggeredAction.m:196
#21	0x000000010ec0ac44 in -[ABKTriggerManager topPriorityTriggerActionForEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:211
#22	0x000000010ec0aafc in -[ABKTriggerManager triggerActionWithFallbacksForEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:201
#23	0x000000010ec0be50 in -[ABKTriggerManager processTriggerEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:364
#24	0x000000010ec0bc4c in -[ABKTriggerManager processPendingTriggerEvents] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:349
#25	0x000000010ec0a9d4 in __51-[ABKTriggerManager handleTriggerFromNotification:]_block_invoke at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:184
#26	0x00000001b3e540f0 in __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ ()
#27	0x00000001b3e28240 in -[NSBlockOperation main] ()
#28	0x00000001b3e281d0 in __NSOPERATION_IS_INVOKING_MAIN__ ()
#29	0x00000001b3de9578 in -[NSOperation start] ()
#30	0x00000001b3de92ac in __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ ()
#31	0x00000001b3dee9c0 in __NSOQSchedule_f ()
#32	0x000000010519f1d0 in _dispatch_block_async_invoke2 ()
#33	0x000000010518e05c in _dispatch_client_callout ()
#34	0x00000001051911e8 in _dispatch_continuation_pop ()
#35	0x0000000105190438 in _dispatch_async_redirect_invoke ()
#36	0x00000001051a2478 in _dispatch_root_queue_drain ()
#37	0x00000001051a2e74 in _dispatch_worker_thread2 ()
#38	0x0000000207ab5dbc in _pthread_wqthread ()
#39	0x0000000207ab5b98 in start_wqthread ()

```

We are using Segment-Appboy 4.6.0 package (which includes Appboy_iOS_SDK 4.5.2).

Context around this happening: We are checking out on Apple Pay, checkout succeeds, and view transitions. But at the moment, this crash occurs. 

Thanks for taking a look.

**Comment by msadoon** [comment]
Hey investigated this a little further and found it to be an issue upgrading from 4.5.0 to 4.6.0, which includes 
```
  "location" : "https://github.com/braze-inc/braze-ios-sdk.git",
      "state" : {
        "revision" : "836548b7b82137a3c04157854919b892ae8e6981",
        "version" : "4.5.0"
        "revision" : "e392a749e525fce80a09844aab0d8fd0a6668fc3",
        "version" : "4.5.3"
      }
```
4.5.0 is fine, no crash, 4.6.0 of braze-ios-sdk causes the crash.

**Comment by lowip** [comment]
Hi @msadoon,

Thanks for opening this issue. The `appboy-segment-ios` wrapper allows you to update minor versions of the base `AppboyKit-iOS-SDK`.

The issue you're facing has actually been fixed in `AppboyKit-iOS-SDK` [`4.5.3`](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#453). The stack traces provided are from `4.5.2` as you mention.

Are you experiencing the crash with `AppboyKit-iOS-SDK` `4.5.3`? If so, can you provide stack traces for this version of the SDK, it may be a different crash.

> PS: If you want to pin a specific version of `AppboyKit-iOS-SDK`, you can add it explicitly to your Podfile. The version still needs to match the version rule [here](https://github.com/Appboy/appboy-segment-ios/blob/08a061113e8a7e835e6bc9c0e1629d94e63aa29e/Segment-Appboy.podspec#L26) (currently `4.5.1` at minima)

**Comment by msadoon** [comment]
Hi @lowip,

Thanks for the quick response.

So I did try this with `AppboyKit-iOS-SDK` version 4.5.3, which comes bundled with `appboy-segment-ios` 4.6.0 and heres' the crash trace, it looks the same to me but maybe not on closer inspection.

Also, I forgot to mention, is there a way to pin `AppboyKit-iOS-SDK` with SPM? I'd like to use `4.5.0` or `4.5.1` if possible.

Debugger info:
```
2023-02-01 17:30:44.949290-0500 Kickstarter[13208:2570872] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean isEqualToString:]: unrecognized selector sent to instance 0x211390e78'
*** First throw call stack:
(0x1b9a2de48 0x1b2d038d8 0x1b9ba282c 0x1b9a43f60 0x1b9aac330 0x10d066758 0x10cff4f3c 0x10cff526c 0x10cff42f8 0x10cff4280 0x10d06ac6c 0x1b9a2e360 0x1b9a49690 0x10d06ab68 0x1b9a2e360 0x1b9ab50c0 0x10d06a9d4 0x10d0432a8 0x10d05619c 0x10d02594c 0x10d0257e8 0x10d026c80 0x10d026a54 0x10d0256b0 0x1b3e540f0 0x1b3e28240 0x1b3e281d0 0x1b3de9578 0x1b3de92ac 0x1b3dee9c0 0x105b731d0 0x105b6205c 0x105b651e8 0x105b64438 0x105b76478 0x105b76e74 0x207ab5dbc 0x207ab5b98)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean isEqualToString:]: unrecognized selector sent to instance 0x211390e78'
terminating with uncaught exception of type NSException
```

Stack trace:

```
Thread 31 Queue : NSOperationQueue 0x14dd48290 (QOS: UNSPECIFIED) (concurrent)
#0	0x00000001f739f160 in __pthread_kill ()
#1	0x0000000207abc1ac in pthread_kill ()
#2	0x00000001c10a4c8c in abort ()
#3	0x00000002079fbb8c in abort_message ()
#4	0x00000002079eba80 in demangling_terminate_handler() ()
#5	0x00000001b2d09d3c in _objc_terminate() ()
#6	0x00000002079faf28 in std::__terminate(void (*)()) ()
#7	0x00000002079faec4 in std::terminate() ()
#8	0x00000001b2d1fbec in objc_terminate ()
#9	0x0000000105b62070 in _dispatch_client_callout ()
#10	0x0000000105b651e8 in _dispatch_continuation_pop ()
#11	0x0000000105b64438 in _dispatch_async_redirect_invoke ()
#12	0x0000000105b76478 in _dispatch_root_queue_drain ()
#13	0x0000000105b76e74 in _dispatch_worker_thread2 ()
#14	0x0000000207ab5dbc in _pthread_wqthread ()
Thread#0	0x00000001b9a2de48 in __exceptionPreprocess ()
#1	0x00000001b2d038d8 in objc_exception_throw ()
#2	0x00000001b9ba282c in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#3	0x00000001b9a43f60 in ___forwarding___ ()
#4	0x00000001b9aac330 in _CF_forwarding_prep_0 ()
#5	0x000000010d066758 in +[ABKUtilityFunctions string:isEqualToString:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/UtilityClasses/ABKUtilityFunctions.m:319
#6	0x000000010cff4f3c in -[ABKTriggerPropertyFilter validatePropertyValueType:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:190
#7	0x000000010cff526c in -[ABKTriggerPropertyFilter validatedValue:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:207
#8	0x000000010cff42f8 in -[ABKTriggerPropertyFilter matchValue:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:78
#9	0x000000010cff4280 in -[ABKTriggerPropertyFilter matchProperties:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKTriggerPropertyFilter.m:72
#10	0x000000010d06ac6c in __38-[ABKPropertyTrigger matchProperties:]_block_invoke_2 at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:49
#11	0x00000001b9a2e360 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#12	0x00000001b9a49690 in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#13	0x000000010d06ab68 in __38-[ABKPropertyTrigger matchProperties:]_block_invoke at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:48
#14	0x00000001b9a2e360 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#15	0x00000001b9ab50c0 in -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] ()
#16	0x000000010d06a9d4 in -[ABKPropertyTrigger matchProperties:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKPropertyTrigger.m:45
#17	0x000000010d0432a8 in -[ABKCustomEventPropertyTrigger match:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerConditions/ABKCustomEventPropertyTrigger.m:21
#18	0x000000010d05619c in -[ABKTriggeredAction respondsToTriggerEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/TriggerActions/ABKTriggeredAction.m:196
#19	0x000000010d02594c in -[ABKTriggerManager topPriorityTriggerActionForEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:211
#20	0x000000010d0257e8 in -[ABKTriggerManager triggerActionWithFallbacksForEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:201
#21	0x000000010d026c80 in -[ABKTriggerManager processTriggerEvent:] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:364
#22	0x000000010d026a54 in -[ABKTriggerManager processPendingTriggerEvents] at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:349
#23	0x000000010d0256b0 in __51-[ABKTriggerManager handleTriggerFromNotification:]_block_invoke at /Users/jerielng/AppboyKit/AppboyKit/AppboyKit/Triggers/ABKTriggerManager.m:184
#24	0x00000001b3e540f0 in __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ ()
#25	0x00000001b3e28240 in -[NSBlockOperation main] ()
#26	0x00000001b3e281d0 in __NSOPERATION_IS_INVOKING_MAIN__ ()
#27	0x00000001b3de9578 in -[NSOperation start] ()
#28	0x00000001b3de92ac in __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ ()
#29	0x00000001b3dee9c0 in __NSOQSchedule_f ()
#30	0x0000000105b731d0 in _dispatch_block_async_invoke2 ()
#31	0x0000000105b6205c in _dispatch_client_callout ()
#32	0x0000000105b651e8 in _dispatch_continuation_pop ()
#33	0x0000000105b64438 in _dispatch_async_redirect_invoke ()
#34	0x0000000105b76478 in _dispatch_root_queue_drain ()
#35	0x0000000105b76e74 in _dispatch_worker_thread2 ()
#36	0x0000000207ab5dbc in _pthread_wqthread ()
#37	0x0000000207ab5b98 in start_wqthread ()
```

**Comment by lowip** [comment]
Thanks for the stack trace,

The issue is actually slightly different, but in a related part of our codebase. This is due to some wrong values for one of the current in-app message campaign for this user. 

Pinning the SDK to `4.5.1` would not resolve the issue, but if you're willing to try, you should be able to do so by explicitly referencing the `Appboy-iOS-SDK` Swift package in your Xcode project using the repository URL `https://github.com/braze-inc/braze-ios-sdk.git`.

You can only pin to `4.5.1` or later patch versions, otherwise SwiftPM will refuse to resolve the packages.

**Comment by msadoon** [comment]
Ok, great thanks for the info @lowip 

I don't mind pinning to `Appboy-iOS-SDK` to `4.5.1` as you suggested but it sounds like the app might still crash in certain scenarios.

With respect to shipping this issue into production, is there a more stable version of `appboy-segment-ios` that you recommend?

Before we migrated to SPM we used version 4.0.0 with Carthage.

**Comment by lowip** [comment]
Hi @msadoon, 

We have a fix for this issue that will be part of the next release, which should be available in a few days. We'll update here once it is available.

> With respect to shipping this issue into production, is there a more stable version of appboy-segment-ios that you recommend?

It would be `4.5.1`. After a deeper look, the issue you are currently experiencing was introduced in `4.5.2` while trying to fix a rare bug of inconsistent in-app message network data.

**Comment by jerielng** [comment]
Hi @msadoon,

We have just released version `4.5.4` of the Appboy iOS SDK, which should resolve the crashes you are seeing. Are you able to verify against this version?

**Comment by msadoon** [comment]
Hi @jerielng @lowip 

That crash scenario seems fixed now. Small note, our dev environment doesn't let us test this crash scenario (Apply Pay) outside a sandbox. Within the sandbox the crash no longer occurs. In about 3 weeks we'll do our full regression test with the latest `appboy-ios-segment` and report any issues if found.

Thanks both for your help on this one!
